library(readxl)
library(maps)

x <- read_excel("/Volumes/GoogleDrive/My Drive/2018-2019/BA Thesis/Data/Data Cleaning/AHA Data/AHA_2014.xlsx")
crosswalk <- read_excel("Enrollment Data/crosswalk.xlsx")
colnames(crosswalk)<-c("county_code", "rating_area")
x <- merge(x, crosswalk, "county_code")
x$id_1 <- ifelse(is.na(x$`System ID`), x$`AHA ID`, x$`System ID`)
x$id_2 <-paste(x$id_1, x$rating_area)
y <- aggregate(x$Admissions, by=list(x$id_2), FUN=sum, na.rm=TRUE)
colnames(y)<-c("id_2", "system_admissions")
z <- merge(x, y, "id_2")
z$dup <-duplicated(z$id_2)
z <-subset(z, z$dup==FALSE)
y <- aggregate(z$Admissions, by=list(z$rating_area), FUN=sum, na.rm=TRUE)
colnames(y) <- c("rating_area", "county_admissions")
z <- merge(z, y, "rating_area")
z$mkt_share_squared <- ((z$Admissions/z$county_admissions)*100)^2
hospital_hhi_2014 <- aggregate(z$mkt_share_squared, by=list(z$rating_area), FUN=sum, na.rm=TRUE)
colnames(hospital_hhi_2014) <- c("rating_area", "hospital_hhi")
hospital_hhi_2014 <-merge(crosswalk, hospital_hhi_2014, "rating_area")
colnames(hospital_hhi_2014)<-c("rating_area", "fips", "hospital_hhi")

x <- read_excel("/Volumes/GoogleDrive/My Drive/2018-2019/BA Thesis/Data/Data Cleaning/AHA Data/AHA_2015.xlsx")
crosswalk <- read_excel("Enrollment Data/crosswalk.xlsx")
colnames(crosswalk)<-c("county_code", "rating_area")
x <- merge(x, crosswalk, "county_code")
x$id_1 <- ifelse(is.na(x$`System ID`), x$`AHA ID`, x$`System ID`)
x$id_2 <-paste(x$id_1, x$rating_area)
y <- aggregate(x$Admissions, by=list(x$id_2), FUN=sum, na.rm=TRUE)
colnames(y)<-c("id_2", "system_admissions")
z <- merge(x, y, "id_2")
z$dup <-duplicated(z$id_2)
z <-subset(z, z$dup==FALSE)
y <- aggregate(z$Admissions, by=list(z$rating_area), FUN=sum, na.rm=TRUE)
colnames(y) <- c("rating_area", "county_admissions")
z <- merge(z, y, "rating_area")
z$mkt_share_squared <- ((z$Admissions/z$county_admissions)*100)^2
hospital_hhi_2015 <- aggregate(z$mkt_share_squared, by=list(z$rating_area), FUN=sum, na.rm=TRUE)
colnames(hospital_hhi_2015) <- c("rating_area", "hospital_hhi")
hospital_hhi_2015 <-merge(crosswalk, hospital_hhi_2015, "rating_area")
colnames(hospital_hhi_2015)<-c("rating_area", "fips", "hospital_hhi")
